prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  enabled: false

nodeExporter:
  enabled: false

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false
